from setuptools import setup

setup(name             = "block_canvas_deps",
      version          = "0.1.0",
      description      = 'Enthought Block Canvas Application dependents',
      author           = 'Enthought, Inc',
      author_email     = 'info@enthought.com',
      url              = 'http://code.enthought.com',
      license          = 'BSD',
      zip_safe         = True,
      install_requires = [
        "enthought.block_canvas",
        "enthought.chaco>=3.0a1",
        "enthought.debug",
        "enthought.enable>=3.0a1",
        "enthought.etsconfig",
        "enthought.greenlet",
        "enthought.io",
        "enthought.kiva",
        "enthought.logger",
        "enthought.naming",
        "enthought.numerical_modeling",
        "enthought.pyface>=3.0a1",
        "enthought.pyface.ui.wx>=3.0a1",
        "enthought.resource",
        "enthought.sweet_pickle",
        "enthought.testing",
        "enthought.traits>=3.0.0b1",
        "enthought.traits.ui.wx>=3.0.0b1",
        "enthought.type_manager",
        "enthought.units",
        "enthought.util",
        "geo",
        "PIL",
        "wxPython>2.6",
        "docutils",
      ],
)
